"""ilk sema: 7 tablo

Revision ID: 194083f2d2aa
Revises:
Create Date: 2026-08-17 14:41:00.309033

`docs/veri-modeli.md` Bölüm 2'deki şemanın tamamı.

ELLE EKLENEN (autogenerate üretmez):
  - `CREATE EXTENSION IF NOT EXISTS pg_trgm` — upgrade'in EN BAŞINDA olmalı,
    yoksa `ix_entity_arama` indeksindeki `gin_trgm_ops` operatör sınıfı
    bulunamaz ve migration patlar. Autogenerate eklenti bağımlılıklarını
    görmez; yalnızca tablo/indeks/kısıt karşılaştırması yapar.
  - downgrade sonunda `DROP EXTENSION` — geri alınabilirlik için (Bölüm 6).

Autogenerate'in DOĞRU ürettiği, elle düzeltme gerektirmeyenler (denetlendi):
  - 7 tablo ve tüm FK'ler (ON DELETE CASCADE / SET NULL dahil)
  - uq_entity, uq_job_tekrar, uq_rel
  - ck_rel_self, ck_job_durum, ck_assess_skor, ck_hyp_guven,
    ck_hyp_analist_durumu, ck_obs_guven, ck_investigation_durum
  - ix_job_kuyruk kısmi indeksi (`postgresql_where`)
  - GIN indeksleri: `nitelikler` (JSONB) ve `deger_norm` (`postgresql_ops`)
  - TIMESTAMPTZ (`DateTime(timezone=True)`) ve tüm server_default'lar
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '194083f2d2aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ELLE EKLENDİ — HER ŞEYDEN ÖNCE. `ix_entity_arama` bu eklentinin sağladığı
    # `gin_trgm_ops` operatör sınıfını kullanır; eklenti yoksa CREATE INDEX
    # "operator class ... does not exist" ile başarısız olur.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ad', sa.Text(), nullable=False),
    sa.Column('kok_hedef', sa.Text(), nullable=False),
    sa.Column('kapsam_notu', sa.Text(), nullable=True),
    sa.Column('yetki_onayi', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('yetki_notu', sa.Text(), nullable=True),
    sa.Column('olusturan', sa.Text(), nullable=False),
    sa.Column('durum', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("durum IN ('active','archived')", name='ck_investigation_durum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigation_durum', 'investigation', ['durum', sa.literal_column('olusturma DESC')], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('tip', sa.Text(), nullable=False),
    sa.Column('deger_norm', sa.Text(), nullable=False),
    sa.Column('deger_ham', sa.Text(), nullable=False),
    sa.Column('nitelikler', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ilk_gorulme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('son_gorulme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gozlem_sayisi', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'tip', 'deger_norm', name='uq_entity')
    )
    op.create_index('ix_entity_arama', 'entity', ['deger_norm'], unique=False, postgresql_using='gin', postgresql_ops={'deger_norm': 'gin_trgm_ops'})
    op.create_index('ix_entity_inv_tip', 'entity', ['investigation_id', 'tip'], unique=False)
    op.create_index('ix_entity_nitelikler', 'entity', ['nitelikler'], unique=False, postgresql_using='gin')
    op.create_index('ix_entity_son_gorulme', 'entity', ['investigation_id', sa.literal_column('son_gorulme DESC')], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('baslik', sa.Text(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('guven', sa.SmallInteger(), nullable=False),
    sa.Column('entity_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_versiyon', sa.Text(), nullable=False),
    sa.Column('analist_durumu', sa.Text(), server_default=sa.text("'beklemede'"), nullable=False),
    sa.Column('zaman', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analist_durumu IN ('beklemede','dogrulandi','reddedildi')", name='ck_hyp_analist_durumu'),
    sa.CheckConstraint('guven BETWEEN 0 AND 100', name='ck_hyp_guven'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hyp_inv', 'hypothesis', ['investigation_id', sa.literal_column('guven DESC')], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('skor', sa.SmallInteger(), nullable=False),
    sa.Column('gerekce', sa.Text(), nullable=False),
    sa.Column('etiketler', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_versiyon', sa.Text(), nullable=False),
    sa.Column('girdi_hash', sa.Text(), nullable=False),
    sa.Column('zaman', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('skor BETWEEN 0 AND 100', name='ck_assess_skor'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assess_entity', 'assessment', ['entity_id', sa.literal_column('zaman DESC')], unique=False)
    op.create_index('ix_assess_skor', 'assessment', [sa.literal_column('skor DESC'), sa.literal_column('zaman DESC')], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=False),
    sa.Column('hedef_entity_id', sa.UUID(), nullable=True),
    sa.Column('hedef_deger', sa.Text(), nullable=False),
    sa.Column('durum', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('derinlik', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.Column('cikis_kodu', sa.Integer(), nullable=True),
    sa.Column('baslangic', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bitis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sure_ms', sa.Integer(), nullable=True),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("durum IN ('queued','running','success','failed','timeout','skipped','cancelled')", name='ck_job_durum'),
    sa.ForeignKeyConstraint(['hedef_entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'tool', 'hedef_deger', name='uq_job_tekrar')
    )
    op.create_index('ix_job_inv_durum', 'job', ['investigation_id', 'durum'], unique=False)
    op.create_index('ix_job_kuyruk', 'job', ['durum', 'olusturma'], unique=False, postgresql_where=sa.text("durum = 'queued'"))
    op.create_table('relationship',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('kaynak_entity_id', sa.UUID(), nullable=False),
    sa.Column('hedef_entity_id', sa.UUID(), nullable=False),
    sa.Column('tip', sa.Text(), nullable=False),
    sa.Column('ilk_gorulme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('son_gorulme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nitelikler', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('kaynak_entity_id <> hedef_entity_id', name='ck_rel_self'),
    sa.ForeignKeyConstraint(['hedef_entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kaynak_entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kaynak_entity_id', 'hedef_entity_id', 'tip', name='uq_rel')
    )
    op.create_index('ix_rel_hedef', 'relationship', ['hedef_entity_id', 'tip'], unique=False)
    op.create_index('ix_rel_inv', 'relationship', ['investigation_id'], unique=False)
    op.create_index('ix_rel_kaynak', 'relationship', ['kaynak_entity_id', 'tip'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=False),
    sa.Column('ham_cikti_ref', sa.Text(), nullable=False),
    sa.Column('ham_cikti_yol', sa.Text(), nullable=True),
    sa.Column('guven', sa.SmallInteger(), server_default=sa.text('50'), nullable=False),
    sa.Column('veri', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('zaman', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('guven BETWEEN 0 AND 100', name='ck_obs_guven'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_entity', 'observation', ['entity_id', sa.literal_column('zaman DESC')], unique=False)
    op.create_index('ix_obs_job', 'observation', ['job_id'], unique=False)
    op.create_index('ix_obs_tool', 'observation', ['tool', sa.literal_column('zaman DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_tool', table_name='observation')
    op.drop_index('ix_obs_job', table_name='observation')
    op.drop_index('ix_obs_entity', table_name='observation')
    op.drop_table('observation')
    op.drop_index('ix_rel_kaynak', table_name='relationship')
    op.drop_index('ix_rel_inv', table_name='relationship')
    op.drop_index('ix_rel_hedef', table_name='relationship')
    op.drop_table('relationship')
    op.drop_index('ix_job_kuyruk', table_name='job', postgresql_where=sa.text("durum = 'queued'"))
    op.drop_index('ix_job_inv_durum', table_name='job')
    op.drop_table('job')
    op.drop_index('ix_assess_skor', table_name='assessment')
    op.drop_index('ix_assess_entity', table_name='assessment')
    op.drop_table('assessment')
    op.drop_index('ix_hyp_inv', table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index('ix_entity_son_gorulme', table_name='entity')
    op.drop_index('ix_entity_nitelikler', table_name='entity', postgresql_using='gin')
    op.drop_index('ix_entity_inv_tip', table_name='entity')
    op.drop_index('ix_entity_arama', table_name='entity', postgresql_using='gin', postgresql_ops={'deger_norm': 'gin_trgm_ops'})
    op.drop_table('entity')
    op.drop_index('ix_investigation_durum', table_name='investigation')
    op.drop_table('investigation')
    # ### end Alembic commands ###

    # ELLE EKLENDİ — EN SONDA. `ix_entity_arama` yukarıda düşürüldüğü için
    # eklentiye bağımlı nesne kalmaz ve CASCADE'siz DROP güvenlidir.
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
