"""job.deneme_sayisi

Revision ID: 71a05e732d14
Revises: 194083f2d2aa
Create Date: 2026-08-26 11:52:52.601949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a05e732d14'
down_revision: Union[str, Sequence[str], None] = '194083f2d2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('deneme_sayisi', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'deneme_sayisi')
    # ### end Alembic commands ###
